- name: Add repository to install Java 8
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present

- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: latest
    install_recommends: no